version: '3.8'

services:
  backend:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy  # Wait for Redis to be ready

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:  # Added healthcheck
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  langflow:
    image: langflowai/langflow:latest
    ports:
      - "7860:7860"
    volumes:
      - ./flows:/app/flows
    environment:
      LANGFLOW_CACHE_TYPE: "redis"
      LANGFLOW_REDIS_HOST: "redis"
      LANGFLOW_REDIS_PORT: "6379"
      LANGFLOW_REDIS_DB: "0"
      LANGFLOW_DEFAULT_FLOWS_PATH: "/app/flows"
      GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
    depends_on:
      - redis
